config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :accounts
  resources :members

  root 'home#index'
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :first_name, presence: true, length: {maximum: 20}
  validates :middle_name, length: {maximum: 10}
  validates :last_name, presence: true, length: {maximum: 40}
  validates :cell_phone, presence: true, length: {minimum: 10, maximum: 16}
  validates :birth_day, presence: true
  validates :ssn, presence: true, length: {is: 9}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
  end

  def create
    @account = Account.new(account_params)

    @account.save
    redirect_to @account
  end

  def show
    @account = Account.find(params[:id])
  end

  private
    def account_params
      params.require(:account).permit(:number, :branch, :account_type, :open_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to @member
    else
      render 'new'
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  private
    def member_params
      params.require(:member).permit(:first_name, :middle_name, :last_name, :home_phone, :work_phone, :cell_phone, :birth_day, :ssn)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= form_with scope: :account, url: accounts_path, local: true do |form| %>
  <p>
    <%= form.label :account_number %><br>
    <%= form.number_field :number %>
  </p>
  <p>
    <%= form.label :branch %><br>
    <%= form.text_field :branch %>
  </p>
  <p>
    <%= form.label :account_type %><br>
    <%= form.text_field :account_type %>
  </p>
  <p>
    <%= form.label :open_date %>
    <%= form.date_select :open_date %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/accounts/show.html.erb
<p>
  <strong>Account Number:</strong>
  <%= @account.number %>
</p>

<p>
  <strong>Account Type:</strong>
  <%= @account.id %>
</p>

<p>
  <strong>Account Branch:</strong>
  <%= @account.branch %>
</p>

<p>
  <strong>Open Date:</strong>
  <%= @account.open_date %>
</p>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= form_with scope: :member, url: members_path, local:true do |form| %>

  <% if @member.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@member.errors.count, 'error') %>
        prohibited this member from being saved:
      </h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :middle_name %><br>
    <%= form.text_field :middle_name %>
  </p>
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :home_phone %><br>
    <%= form.text_field :home_phone %>
  </p>
  <p>
    <%= form.label :work_phone %><br>
    <%= form.text_field :work_phone %>
  </p>
  <p>
    <%= form.label :cell_phone %><br>
    <%= form.text_field :cell_phone %>
  </p>
  <p>
    <%= form.label :birthday %><br>
    <%= form.date_field :birth_day %>
  </p>
  <p>
    <%= form.label :ssn %><br>
    <%= form.text_field :ssn %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/members/show.html.erb
<p>
  <strong>Member:</strong>
  <%= "#{@member.first_name} #{@member.last_name}" %>
</p>
<p>
  <strong>Member Number:</strong>
  <%= @member.id %>
</p>
<p>
  <strong>Home Phone:</strong>
  <%= @member.home_phone%>
</p>
<p>
  <strong>Work Phone:</strong>
  <%= @member.work_phone %>
</p>
<p>
  <strong>Mobile Phone:</strong>
  <%= @member.cell_phone %>
</p>
<p>
  <strong>Birthday:</strong>
  <%= @member.birth_day %>
</p>
<p>
  <strong>SSN:</strong>
  <%= @member.ssn %>
</p>